import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../../components/navbar/navbar.js"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="{inter.className} bg-[#0c0c23]">
        <NavBar/>
        <div className="bg-[#0c0c23] text-white font-arial h-full w-full">
        {children}  
        </div>
      </body>
    </html>
  );
}

